name: Release CEF Artifacts

on:
  push:
    branches:
      - release/v*

defaults:
  run:
    shell: bash

permissions:
  contents: write

env:
  CEF_VERSION: v138

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            url: "https://cef-builds.spotifycdn.com/cef_binary_138.0.49%2Bg5ae25f5%2Bchromium-138.0.7204.261_windows64_minimal.tar.bz2"
            artifact_name: cef-windows-x86_64
            extract_cmd: "7z x"
            compress_cmd: "7z a -tzip"
            
          - os: macos-latest
            url: "https://cef-builds.spotifycdn.com/cef_binary_138.0.51%2Bg41d93d2%2Bchromium-138.0.7204.293_macosarm64_minimal.tar.bz2"
            artifact_name: cef-macos-arm64
            extract_cmd: "tar -xjf"
            compress_cmd: "zip -r"

          - os: macos-latest
            url: "https://cef-builds.spotifycdn.com/cef_binary_138.0.51%2Bg41d93d2%2Bchromium-138.0.7204.293_macosx64_minimal.tar.bz2"
            artifact_name: cef-macos-x86_64
            extract_cmd: "tar -xjf"
            compress_cmd: "zip -r"
            flags: "--target x86_64-apple-darwin"
            
          - os: ubuntu-latest
            url: "https://cef-builds.spotifycdn.com/cef_binary_138.0.51%2Bg41d93d2%2Bchromium-138.0.7204.293_linux64_minimal.tar.bz2"
            artifact_name: cef-linux-x86_64
            extract_cmd: "tar -xjf"
            compress_cmd: "zip -r"
            
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create artifacts directory
      run: mkdir artifacts
      
    - name: Download CEF build
      run: |
        curl -L --http1.1 "${{ matrix.url }}" -o artifacts/cef.tar.bz2
          
    - name: Extract archive
      run: |
        cd artifacts
        ${{ matrix.extract_cmd }} cef.tar.bz2    
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ${{ matrix.extract_cmd }} *.tar
        fi
        mv cef_binary_*/* .
        
    - name: Process CEF artifacts
      run: |
        rustup target add x86_64-apple-darwin
        cargo run --bin cef-artifacts --release ${{ matrix.flags }}
        cargo cef-artifacts

    - name: Build CEF Simple
      run: |
        export CEF_ARTIFACTS_DIR=$(pwd)/artifacts/cef
        cargo run --bin cef-build --release ${{ matrix.flags }} -- --profile release ${{ matrix.flags }}
        
    - name: Create artifact
      run: |
        cd artifacts/cef
        ${{ matrix.compress_cmd }} ${{ matrix.artifact_name }}.zip *

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if gh release view "$CEF_VERSION" > /dev/null 2>&1; then
          gh release upload "$CEF_VERSION" artifacts/cef/${{ matrix.artifact_name }}.zip
        else
          gh release create "$CEF_VERSION" \
            --title "CEF $CEF_VERSION Binaries" \
            artifacts/cef/${{ matrix.artifact_name }}.zip
        fi
